// Code generated by protoc-gen-twirp v5.3.0, DO NOT EDIT.
// source: devicereg.proto

/*
Package devicereg is a generated twirp stub package.
This code was generated with github.com/twitchtv/twirp/protoc-gen-twirp v5.3.0.

It is generated from these files:
	devicereg.proto
*/
package devicereg

import bytes "bytes"
import strings "strings"
import context "context"
import fmt "fmt"
import ioutil "io/ioutil"
import http "net/http"

import jsonpb "github.com/golang/protobuf/jsonpb"
import proto "github.com/golang/protobuf/proto"
import twirp "github.com/twitchtv/twirp"
import ctxsetters "github.com/twitchtv/twirp/ctxsetters"

// Imports only used by utility functions:
import io "io"
import strconv "strconv"
import json "encoding/json"
import url "net/url"

// ============================
// DeviceRegistration Interface
// ============================

// DeviceRegistration is our service that provides the top level interface which
// starts the process of claiming a device and ultimately create entitlements.
// This service will eventually be the service that orchestrates the flow
// between the DECODE wallet, and SmartCitizen's onboarding process and provide
// the mechanism for managing entitlements via the wallet. For now we simply
// expose two methods which allow a simulated device to be claimed and revoked.
type DeviceRegistration interface {
	// ClaimDevice here is what starts the flow off of registering and configuring
	// a device. It takes as input a message containing a device token
	// (identifying the device), a user uid (which is the decode user id), as well
	// as the devices real world location and some other metadata about the
	// device. The outcome of this call in the first iteration of the system, is
	// that we would call down to the stream encoder to create an encrypted stream
	// for the device that will be accessible from the datastore.
	ClaimDevice(context.Context, *ClaimDeviceRequest) (*ClaimDeviceResponse, error)

	// RevokeDevice here should delete all config for the device stored within
	// the device registration service, which must also delete all streams by
	// calling down to the stream encoder.
	RevokeDevice(context.Context, *RevokeDeviceRequest) (*RevokeDeviceResponse, error)

	// CreateEntitlementPolicy is a method exposed by the service which allows a
	// new entitlement policy to be created and stored within the device
	// registration service. Once a policy has been created, users will then be
	// able to apply this policy to their devices via the wallet.
	CreateEntitlementPolicy(context.Context, *CreateEntitlementPolicyRequest) (*CreateEntitlementPolicyResponse, error)

	// DeleteEntitlementPolicy is a method exposed by the service which allows an
	// authorized client to request that an entitlement policy be deleted.
	// Deleting a policy will not affect any existing devices that have already
	// used the policy in order to create one or more streams within the encoder,
	// however it will prevent any new applications of that policy to other
	// devices.
	DeleteEntitlementPolicy(context.Context, *DeleteEntitlementPolicyRequest) (*DeleteEntitlementPolicyResponse, error)

	// ListEntitlementPolicies is a method exposed by the service which returns a
	// list of all policies currently defined and available within the service to
	// be applied to devices. Currently it just returns a list of all known
	// policies with no capability to filter or paginate these policies.
	ListEntitlementPolicies(context.Context, *ListEntitlementPoliciesRequest) (*ListEntitlementPoliciesResponse, error)

	// ApplyEntitlement is a method exposed by the service which allows a user who
	// has previously claimed a device to apply specific entitlement policies to
	// their device. Applying a policy to a device sets up a new stream on the
	// stream encoder with the filtering or aggregation functions defined in the
	// policy applied to incoming events. This will result in the stream encoder
	// encrypting and emitting the processed events to the datastore for the
	// specified policy. Note we send the same request message for both this and
	// RevokeEntitlement as the data sent is exactly the same.
	ApplyEntitlement(context.Context, *EntitlementRequest) (*ApplyEntitlementResponse, error)

	// RevokeEntitlement is a method exposed by the service which allows a user
	// who has previously claimed a device to revoke specific entitlement policies
	// from their device. Revoking a policy from a device causes the service to
	// delete associated streams meaning data will no longer be encrypted and sent
	// to the datastore. Note we send the same request message for both this and
	// ApplyEntitlement as the data sent is exactly the same.
	RevokeEntitlement(context.Context, *EntitlementRequest) (*RevokeEntitlementResponse, error)
}

// ==================================
// DeviceRegistration Protobuf Client
// ==================================

type deviceRegistrationProtobufClient struct {
	client HTTPClient
	urls   [7]string
}

// NewDeviceRegistrationProtobufClient creates a Protobuf client that implements the DeviceRegistration interface.
// It communicates using Protobuf and can be configured with a custom HTTPClient.
func NewDeviceRegistrationProtobufClient(addr string, client HTTPClient) DeviceRegistration {
	prefix := urlBase(addr) + DeviceRegistrationPathPrefix
	urls := [7]string{
		prefix + "ClaimDevice",
		prefix + "RevokeDevice",
		prefix + "CreateEntitlementPolicy",
		prefix + "DeleteEntitlementPolicy",
		prefix + "ListEntitlementPolicies",
		prefix + "ApplyEntitlement",
		prefix + "RevokeEntitlement",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &deviceRegistrationProtobufClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &deviceRegistrationProtobufClient{
		client: client,
		urls:   urls,
	}
}

func (c *deviceRegistrationProtobufClient) ClaimDevice(ctx context.Context, in *ClaimDeviceRequest) (*ClaimDeviceResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "devicereg")
	ctx = ctxsetters.WithServiceName(ctx, "DeviceRegistration")
	ctx = ctxsetters.WithMethodName(ctx, "ClaimDevice")
	out := new(ClaimDeviceResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

func (c *deviceRegistrationProtobufClient) RevokeDevice(ctx context.Context, in *RevokeDeviceRequest) (*RevokeDeviceResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "devicereg")
	ctx = ctxsetters.WithServiceName(ctx, "DeviceRegistration")
	ctx = ctxsetters.WithMethodName(ctx, "RevokeDevice")
	out := new(RevokeDeviceResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[1], in, out)
	return out, err
}

func (c *deviceRegistrationProtobufClient) CreateEntitlementPolicy(ctx context.Context, in *CreateEntitlementPolicyRequest) (*CreateEntitlementPolicyResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "devicereg")
	ctx = ctxsetters.WithServiceName(ctx, "DeviceRegistration")
	ctx = ctxsetters.WithMethodName(ctx, "CreateEntitlementPolicy")
	out := new(CreateEntitlementPolicyResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[2], in, out)
	return out, err
}

func (c *deviceRegistrationProtobufClient) DeleteEntitlementPolicy(ctx context.Context, in *DeleteEntitlementPolicyRequest) (*DeleteEntitlementPolicyResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "devicereg")
	ctx = ctxsetters.WithServiceName(ctx, "DeviceRegistration")
	ctx = ctxsetters.WithMethodName(ctx, "DeleteEntitlementPolicy")
	out := new(DeleteEntitlementPolicyResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[3], in, out)
	return out, err
}

func (c *deviceRegistrationProtobufClient) ListEntitlementPolicies(ctx context.Context, in *ListEntitlementPoliciesRequest) (*ListEntitlementPoliciesResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "devicereg")
	ctx = ctxsetters.WithServiceName(ctx, "DeviceRegistration")
	ctx = ctxsetters.WithMethodName(ctx, "ListEntitlementPolicies")
	out := new(ListEntitlementPoliciesResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[4], in, out)
	return out, err
}

func (c *deviceRegistrationProtobufClient) ApplyEntitlement(ctx context.Context, in *EntitlementRequest) (*ApplyEntitlementResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "devicereg")
	ctx = ctxsetters.WithServiceName(ctx, "DeviceRegistration")
	ctx = ctxsetters.WithMethodName(ctx, "ApplyEntitlement")
	out := new(ApplyEntitlementResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[5], in, out)
	return out, err
}

func (c *deviceRegistrationProtobufClient) RevokeEntitlement(ctx context.Context, in *EntitlementRequest) (*RevokeEntitlementResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "devicereg")
	ctx = ctxsetters.WithServiceName(ctx, "DeviceRegistration")
	ctx = ctxsetters.WithMethodName(ctx, "RevokeEntitlement")
	out := new(RevokeEntitlementResponse)
	err := doProtobufRequest(ctx, c.client, c.urls[6], in, out)
	return out, err
}

// ==============================
// DeviceRegistration JSON Client
// ==============================

type deviceRegistrationJSONClient struct {
	client HTTPClient
	urls   [7]string
}

// NewDeviceRegistrationJSONClient creates a JSON client that implements the DeviceRegistration interface.
// It communicates using JSON and can be configured with a custom HTTPClient.
func NewDeviceRegistrationJSONClient(addr string, client HTTPClient) DeviceRegistration {
	prefix := urlBase(addr) + DeviceRegistrationPathPrefix
	urls := [7]string{
		prefix + "ClaimDevice",
		prefix + "RevokeDevice",
		prefix + "CreateEntitlementPolicy",
		prefix + "DeleteEntitlementPolicy",
		prefix + "ListEntitlementPolicies",
		prefix + "ApplyEntitlement",
		prefix + "RevokeEntitlement",
	}
	if httpClient, ok := client.(*http.Client); ok {
		return &deviceRegistrationJSONClient{
			client: withoutRedirects(httpClient),
			urls:   urls,
		}
	}
	return &deviceRegistrationJSONClient{
		client: client,
		urls:   urls,
	}
}

func (c *deviceRegistrationJSONClient) ClaimDevice(ctx context.Context, in *ClaimDeviceRequest) (*ClaimDeviceResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "devicereg")
	ctx = ctxsetters.WithServiceName(ctx, "DeviceRegistration")
	ctx = ctxsetters.WithMethodName(ctx, "ClaimDevice")
	out := new(ClaimDeviceResponse)
	err := doJSONRequest(ctx, c.client, c.urls[0], in, out)
	return out, err
}

func (c *deviceRegistrationJSONClient) RevokeDevice(ctx context.Context, in *RevokeDeviceRequest) (*RevokeDeviceResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "devicereg")
	ctx = ctxsetters.WithServiceName(ctx, "DeviceRegistration")
	ctx = ctxsetters.WithMethodName(ctx, "RevokeDevice")
	out := new(RevokeDeviceResponse)
	err := doJSONRequest(ctx, c.client, c.urls[1], in, out)
	return out, err
}

func (c *deviceRegistrationJSONClient) CreateEntitlementPolicy(ctx context.Context, in *CreateEntitlementPolicyRequest) (*CreateEntitlementPolicyResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "devicereg")
	ctx = ctxsetters.WithServiceName(ctx, "DeviceRegistration")
	ctx = ctxsetters.WithMethodName(ctx, "CreateEntitlementPolicy")
	out := new(CreateEntitlementPolicyResponse)
	err := doJSONRequest(ctx, c.client, c.urls[2], in, out)
	return out, err
}

func (c *deviceRegistrationJSONClient) DeleteEntitlementPolicy(ctx context.Context, in *DeleteEntitlementPolicyRequest) (*DeleteEntitlementPolicyResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "devicereg")
	ctx = ctxsetters.WithServiceName(ctx, "DeviceRegistration")
	ctx = ctxsetters.WithMethodName(ctx, "DeleteEntitlementPolicy")
	out := new(DeleteEntitlementPolicyResponse)
	err := doJSONRequest(ctx, c.client, c.urls[3], in, out)
	return out, err
}

func (c *deviceRegistrationJSONClient) ListEntitlementPolicies(ctx context.Context, in *ListEntitlementPoliciesRequest) (*ListEntitlementPoliciesResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "devicereg")
	ctx = ctxsetters.WithServiceName(ctx, "DeviceRegistration")
	ctx = ctxsetters.WithMethodName(ctx, "ListEntitlementPolicies")
	out := new(ListEntitlementPoliciesResponse)
	err := doJSONRequest(ctx, c.client, c.urls[4], in, out)
	return out, err
}

func (c *deviceRegistrationJSONClient) ApplyEntitlement(ctx context.Context, in *EntitlementRequest) (*ApplyEntitlementResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "devicereg")
	ctx = ctxsetters.WithServiceName(ctx, "DeviceRegistration")
	ctx = ctxsetters.WithMethodName(ctx, "ApplyEntitlement")
	out := new(ApplyEntitlementResponse)
	err := doJSONRequest(ctx, c.client, c.urls[5], in, out)
	return out, err
}

func (c *deviceRegistrationJSONClient) RevokeEntitlement(ctx context.Context, in *EntitlementRequest) (*RevokeEntitlementResponse, error) {
	ctx = ctxsetters.WithPackageName(ctx, "devicereg")
	ctx = ctxsetters.WithServiceName(ctx, "DeviceRegistration")
	ctx = ctxsetters.WithMethodName(ctx, "RevokeEntitlement")
	out := new(RevokeEntitlementResponse)
	err := doJSONRequest(ctx, c.client, c.urls[6], in, out)
	return out, err
}

// =================================
// DeviceRegistration Server Handler
// =================================

type deviceRegistrationServer struct {
	DeviceRegistration
	hooks *twirp.ServerHooks
}

func NewDeviceRegistrationServer(svc DeviceRegistration, hooks *twirp.ServerHooks) TwirpServer {
	return &deviceRegistrationServer{
		DeviceRegistration: svc,
		hooks:              hooks,
	}
}

// writeError writes an HTTP response with a valid Twirp error format, and triggers hooks.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func (s *deviceRegistrationServer) writeError(ctx context.Context, resp http.ResponseWriter, err error) {
	writeError(ctx, resp, err, s.hooks)
}

// DeviceRegistrationPathPrefix is used for all URL paths on a twirp DeviceRegistration server.
// Requests are always: POST DeviceRegistrationPathPrefix/method
// It can be used in an HTTP mux to route twirp requests along with non-twirp requests on other routes.
const DeviceRegistrationPathPrefix = "/twirp/devicereg.DeviceRegistration/"

func (s *deviceRegistrationServer) ServeHTTP(resp http.ResponseWriter, req *http.Request) {
	ctx := req.Context()
	ctx = ctxsetters.WithPackageName(ctx, "devicereg")
	ctx = ctxsetters.WithServiceName(ctx, "DeviceRegistration")
	ctx = ctxsetters.WithResponseWriter(ctx, resp)

	var err error
	ctx, err = callRequestReceived(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	if req.Method != "POST" {
		msg := fmt.Sprintf("unsupported method %q (only POST is allowed)", req.Method)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}

	switch req.URL.Path {
	case "/twirp/devicereg.DeviceRegistration/ClaimDevice":
		s.serveClaimDevice(ctx, resp, req)
		return
	case "/twirp/devicereg.DeviceRegistration/RevokeDevice":
		s.serveRevokeDevice(ctx, resp, req)
		return
	case "/twirp/devicereg.DeviceRegistration/CreateEntitlementPolicy":
		s.serveCreateEntitlementPolicy(ctx, resp, req)
		return
	case "/twirp/devicereg.DeviceRegistration/DeleteEntitlementPolicy":
		s.serveDeleteEntitlementPolicy(ctx, resp, req)
		return
	case "/twirp/devicereg.DeviceRegistration/ListEntitlementPolicies":
		s.serveListEntitlementPolicies(ctx, resp, req)
		return
	case "/twirp/devicereg.DeviceRegistration/ApplyEntitlement":
		s.serveApplyEntitlement(ctx, resp, req)
		return
	case "/twirp/devicereg.DeviceRegistration/RevokeEntitlement":
		s.serveRevokeEntitlement(ctx, resp, req)
		return
	default:
		msg := fmt.Sprintf("no handler for path %q", req.URL.Path)
		err = badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, err)
		return
	}
}

func (s *deviceRegistrationServer) serveClaimDevice(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveClaimDeviceJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveClaimDeviceProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *deviceRegistrationServer) serveClaimDeviceJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ClaimDevice")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(ClaimDeviceRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *ClaimDeviceResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.ClaimDevice(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ClaimDeviceResponse and nil error while calling ClaimDevice. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *deviceRegistrationServer) serveClaimDeviceProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ClaimDevice")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(ClaimDeviceRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *ClaimDeviceResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.ClaimDevice(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ClaimDeviceResponse and nil error while calling ClaimDevice. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *deviceRegistrationServer) serveRevokeDevice(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveRevokeDeviceJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveRevokeDeviceProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *deviceRegistrationServer) serveRevokeDeviceJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "RevokeDevice")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(RevokeDeviceRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *RevokeDeviceResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.RevokeDevice(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *RevokeDeviceResponse and nil error while calling RevokeDevice. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *deviceRegistrationServer) serveRevokeDeviceProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "RevokeDevice")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(RevokeDeviceRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *RevokeDeviceResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.RevokeDevice(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *RevokeDeviceResponse and nil error while calling RevokeDevice. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *deviceRegistrationServer) serveCreateEntitlementPolicy(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveCreateEntitlementPolicyJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveCreateEntitlementPolicyProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *deviceRegistrationServer) serveCreateEntitlementPolicyJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CreateEntitlementPolicy")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(CreateEntitlementPolicyRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *CreateEntitlementPolicyResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.CreateEntitlementPolicy(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *CreateEntitlementPolicyResponse and nil error while calling CreateEntitlementPolicy. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *deviceRegistrationServer) serveCreateEntitlementPolicyProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "CreateEntitlementPolicy")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(CreateEntitlementPolicyRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *CreateEntitlementPolicyResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.CreateEntitlementPolicy(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *CreateEntitlementPolicyResponse and nil error while calling CreateEntitlementPolicy. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *deviceRegistrationServer) serveDeleteEntitlementPolicy(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveDeleteEntitlementPolicyJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveDeleteEntitlementPolicyProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *deviceRegistrationServer) serveDeleteEntitlementPolicyJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "DeleteEntitlementPolicy")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(DeleteEntitlementPolicyRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *DeleteEntitlementPolicyResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.DeleteEntitlementPolicy(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *DeleteEntitlementPolicyResponse and nil error while calling DeleteEntitlementPolicy. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *deviceRegistrationServer) serveDeleteEntitlementPolicyProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "DeleteEntitlementPolicy")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(DeleteEntitlementPolicyRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *DeleteEntitlementPolicyResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.DeleteEntitlementPolicy(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *DeleteEntitlementPolicyResponse and nil error while calling DeleteEntitlementPolicy. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *deviceRegistrationServer) serveListEntitlementPolicies(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveListEntitlementPoliciesJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveListEntitlementPoliciesProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *deviceRegistrationServer) serveListEntitlementPoliciesJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListEntitlementPolicies")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(ListEntitlementPoliciesRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *ListEntitlementPoliciesResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.ListEntitlementPolicies(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ListEntitlementPoliciesResponse and nil error while calling ListEntitlementPolicies. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *deviceRegistrationServer) serveListEntitlementPoliciesProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ListEntitlementPolicies")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(ListEntitlementPoliciesRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *ListEntitlementPoliciesResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.ListEntitlementPolicies(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ListEntitlementPoliciesResponse and nil error while calling ListEntitlementPolicies. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *deviceRegistrationServer) serveApplyEntitlement(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveApplyEntitlementJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveApplyEntitlementProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *deviceRegistrationServer) serveApplyEntitlementJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ApplyEntitlement")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(EntitlementRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *ApplyEntitlementResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.ApplyEntitlement(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ApplyEntitlementResponse and nil error while calling ApplyEntitlement. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *deviceRegistrationServer) serveApplyEntitlementProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "ApplyEntitlement")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(EntitlementRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *ApplyEntitlementResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.ApplyEntitlement(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *ApplyEntitlementResponse and nil error while calling ApplyEntitlement. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *deviceRegistrationServer) serveRevokeEntitlement(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	header := req.Header.Get("Content-Type")
	i := strings.Index(header, ";")
	if i == -1 {
		i = len(header)
	}
	switch strings.TrimSpace(strings.ToLower(header[:i])) {
	case "application/json":
		s.serveRevokeEntitlementJSON(ctx, resp, req)
	case "application/protobuf":
		s.serveRevokeEntitlementProtobuf(ctx, resp, req)
	default:
		msg := fmt.Sprintf("unexpected Content-Type: %q", req.Header.Get("Content-Type"))
		twerr := badRouteError(msg, req.Method, req.URL.Path)
		s.writeError(ctx, resp, twerr)
	}
}

func (s *deviceRegistrationServer) serveRevokeEntitlementJSON(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "RevokeEntitlement")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	reqContent := new(EntitlementRequest)
	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(req.Body, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request json")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *RevokeEntitlementResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.RevokeEntitlement(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *RevokeEntitlementResponse and nil error while calling RevokeEntitlement. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	var buf bytes.Buffer
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(&buf, respContent); err != nil {
		err = wrapErr(err, "failed to marshal json response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/json")
	resp.WriteHeader(http.StatusOK)

	respBytes := buf.Bytes()
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *deviceRegistrationServer) serveRevokeEntitlementProtobuf(ctx context.Context, resp http.ResponseWriter, req *http.Request) {
	var err error
	ctx = ctxsetters.WithMethodName(ctx, "RevokeEntitlement")
	ctx, err = callRequestRouted(ctx, s.hooks)
	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}

	buf, err := ioutil.ReadAll(req.Body)
	if err != nil {
		err = wrapErr(err, "failed to read request body")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}
	reqContent := new(EntitlementRequest)
	if err = proto.Unmarshal(buf, reqContent); err != nil {
		err = wrapErr(err, "failed to parse request proto")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	// Call service method
	var respContent *RevokeEntitlementResponse
	func() {
		defer func() {
			// In case of a panic, serve a 500 error and then panic.
			if r := recover(); r != nil {
				s.writeError(ctx, resp, twirp.InternalError("Internal service panic"))
				panic(r)
			}
		}()
		respContent, err = s.RevokeEntitlement(ctx, reqContent)
	}()

	if err != nil {
		s.writeError(ctx, resp, err)
		return
	}
	if respContent == nil {
		s.writeError(ctx, resp, twirp.InternalError("received a nil *RevokeEntitlementResponse and nil error while calling RevokeEntitlement. nil responses are not supported"))
		return
	}

	ctx = callResponsePrepared(ctx, s.hooks)

	respBytes, err := proto.Marshal(respContent)
	if err != nil {
		err = wrapErr(err, "failed to marshal proto response")
		s.writeError(ctx, resp, twirp.InternalErrorWith(err))
		return
	}

	ctx = ctxsetters.WithStatusCode(ctx, http.StatusOK)
	resp.Header().Set("Content-Type", "application/protobuf")
	resp.WriteHeader(http.StatusOK)
	if n, err := resp.Write(respBytes); err != nil {
		msg := fmt.Sprintf("failed to write response, %d of %d bytes written: %s", n, len(respBytes), err.Error())
		twerr := twirp.NewError(twirp.Unknown, msg)
		callError(ctx, s.hooks, twerr)
	}
	callResponseSent(ctx, s.hooks)
}

func (s *deviceRegistrationServer) ServiceDescriptor() ([]byte, int) {
	return twirpFileDescriptor0, 0
}

func (s *deviceRegistrationServer) ProtocGenTwirpVersion() string {
	return "v5.3.0"
}

// =====
// Utils
// =====

// HTTPClient is the interface used by generated clients to send HTTP requests.
// It is fulfilled by *(net/http).Client, which is sufficient for most users.
// Users can provide their own implementation for special retry policies.
//
// HTTPClient implementations should not follow redirects. Redirects are
// automatically disabled if *(net/http).Client is passed to client
// constructors. See the withoutRedirects function in this file for more
// details.
type HTTPClient interface {
	Do(req *http.Request) (*http.Response, error)
}

// TwirpServer is the interface generated server structs will support: they're
// HTTP handlers with additional methods for accessing metadata about the
// service. Those accessors are a low-level API for building reflection tools.
// Most people can think of TwirpServers as just http.Handlers.
type TwirpServer interface {
	http.Handler
	// ServiceDescriptor returns gzipped bytes describing the .proto file that
	// this service was generated from. Once unzipped, the bytes can be
	// unmarshalled as a
	// github.com/golang/protobuf/protoc-gen-go/descriptor.FileDescriptorProto.
	//
	// The returned integer is the index of this particular service within that
	// FileDescriptorProto's 'Service' slice of ServiceDescriptorProtos. This is a
	// low-level field, expected to be used for reflection.
	ServiceDescriptor() ([]byte, int)
	// ProtocGenTwirpVersion is the semantic version string of the version of
	// twirp used to generate this file.
	ProtocGenTwirpVersion() string
}

// WriteError writes an HTTP response with a valid Twirp error format.
// If err is not a twirp.Error, it will get wrapped with twirp.InternalErrorWith(err)
func WriteError(resp http.ResponseWriter, err error) {
	writeError(context.Background(), resp, err, nil)
}

// writeError writes Twirp errors in the response and triggers hooks.
func writeError(ctx context.Context, resp http.ResponseWriter, err error, hooks *twirp.ServerHooks) {
	// Non-twirp errors are wrapped as Internal (default)
	twerr, ok := err.(twirp.Error)
	if !ok {
		twerr = twirp.InternalErrorWith(err)
	}

	statusCode := twirp.ServerHTTPStatusFromErrorCode(twerr.Code())
	ctx = ctxsetters.WithStatusCode(ctx, statusCode)
	ctx = callError(ctx, hooks, twerr)

	resp.Header().Set("Content-Type", "application/json") // Error responses are always JSON (instead of protobuf)
	resp.WriteHeader(statusCode)                          // HTTP response status code

	respBody := marshalErrorToJSON(twerr)
	_, writeErr := resp.Write(respBody)
	if writeErr != nil {
		// We have three options here. We could log the error, call the Error
		// hook, or just silently ignore the error.
		//
		// Logging is unacceptable because we don't have a user-controlled
		// logger; writing out to stderr without permission is too rude.
		//
		// Calling the Error hook would confuse users: it would mean the Error
		// hook got called twice for one request, which is likely to lead to
		// duplicated log messages and metrics, no matter how well we document
		// the behavior.
		//
		// Silently ignoring the error is our least-bad option. It's highly
		// likely that the connection is broken and the original 'err' says
		// so anyway.
		_ = writeErr
	}

	callResponseSent(ctx, hooks)
}

// urlBase helps ensure that addr specifies a scheme. If it is unparsable
// as a URL, it returns addr unchanged.
func urlBase(addr string) string {
	// If the addr specifies a scheme, use it. If not, default to
	// http. If url.Parse fails on it, return it unchanged.
	url, err := url.Parse(addr)
	if err != nil {
		return addr
	}
	if url.Scheme == "" {
		url.Scheme = "http"
	}
	return url.String()
}

// getCustomHTTPReqHeaders retrieves a copy of any headers that are set in
// a context through the twirp.WithHTTPRequestHeaders function.
// If there are no headers set, or if they have the wrong type, nil is returned.
func getCustomHTTPReqHeaders(ctx context.Context) http.Header {
	header, ok := twirp.HTTPRequestHeaders(ctx)
	if !ok || header == nil {
		return nil
	}
	copied := make(http.Header)
	for k, vv := range header {
		if vv == nil {
			copied[k] = nil
			continue
		}
		copied[k] = make([]string, len(vv))
		copy(copied[k], vv)
	}
	return copied
}

// newRequest makes an http.Request from a client, adding common headers.
func newRequest(ctx context.Context, url string, reqBody io.Reader, contentType string) (*http.Request, error) {
	req, err := http.NewRequest("POST", url, reqBody)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if customHeader := getCustomHTTPReqHeaders(ctx); customHeader != nil {
		req.Header = customHeader
	}
	req.Header.Set("Accept", contentType)
	req.Header.Set("Content-Type", contentType)
	req.Header.Set("Twirp-Version", "v5.3.0")
	return req, nil
}

// JSON serialization for errors
type twerrJSON struct {
	Code string            `json:"code"`
	Msg  string            `json:"msg"`
	Meta map[string]string `json:"meta,omitempty"`
}

// marshalErrorToJSON returns JSON from a twirp.Error, that can be used as HTTP error response body.
// If serialization fails, it will use a descriptive Internal error instead.
func marshalErrorToJSON(twerr twirp.Error) []byte {
	// make sure that msg is not too large
	msg := twerr.Msg()
	if len(msg) > 1e6 {
		msg = msg[:1e6]
	}

	tj := twerrJSON{
		Code: string(twerr.Code()),
		Msg:  msg,
		Meta: twerr.MetaMap(),
	}

	buf, err := json.Marshal(&tj)
	if err != nil {
		buf = []byte("{\"type\": \"" + twirp.Internal + "\", \"msg\": \"There was an error but it could not be serialized into JSON\"}") // fallback
	}

	return buf
}

// errorFromResponse builds a twirp.Error from a non-200 HTTP response.
// If the response has a valid serialized Twirp error, then it's returned.
// If not, the response status code is used to generate a similar twirp
// error. See twirpErrorFromIntermediary for more info on intermediary errors.
func errorFromResponse(resp *http.Response) twirp.Error {
	statusCode := resp.StatusCode
	statusText := http.StatusText(statusCode)

	if isHTTPRedirect(statusCode) {
		// Unexpected redirect: it must be an error from an intermediary.
		// Twirp clients don't follow redirects automatically, Twirp only handles
		// POST requests, redirects should only happen on GET and HEAD requests.
		location := resp.Header.Get("Location")
		msg := fmt.Sprintf("unexpected HTTP status code %d %q received, Location=%q", statusCode, statusText, location)
		return twirpErrorFromIntermediary(statusCode, msg, location)
	}

	respBodyBytes, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return clientError("failed to read server error response body", err)
	}
	var tj twerrJSON
	if err := json.Unmarshal(respBodyBytes, &tj); err != nil {
		// Invalid JSON response; it must be an error from an intermediary.
		msg := fmt.Sprintf("Error from intermediary with HTTP status code %d %q", statusCode, statusText)
		return twirpErrorFromIntermediary(statusCode, msg, string(respBodyBytes))
	}

	errorCode := twirp.ErrorCode(tj.Code)
	if !twirp.IsValidErrorCode(errorCode) {
		msg := "invalid type returned from server error response: " + tj.Code
		return twirp.InternalError(msg)
	}

	twerr := twirp.NewError(errorCode, tj.Msg)
	for k, v := range tj.Meta {
		twerr = twerr.WithMeta(k, v)
	}
	return twerr
}

// twirpErrorFromIntermediary maps HTTP errors from non-twirp sources to twirp errors.
// The mapping is similar to gRPC: https://github.com/grpc/grpc/blob/master/doc/http-grpc-status-mapping.md.
// Returned twirp Errors have some additional metadata for inspection.
func twirpErrorFromIntermediary(status int, msg string, bodyOrLocation string) twirp.Error {
	var code twirp.ErrorCode
	if isHTTPRedirect(status) { // 3xx
		code = twirp.Internal
	} else {
		switch status {
		case 400: // Bad Request
			code = twirp.Internal
		case 401: // Unauthorized
			code = twirp.Unauthenticated
		case 403: // Forbidden
			code = twirp.PermissionDenied
		case 404: // Not Found
			code = twirp.BadRoute
		case 429, 502, 503, 504: // Too Many Requests, Bad Gateway, Service Unavailable, Gateway Timeout
			code = twirp.Unavailable
		default: // All other codes
			code = twirp.Unknown
		}
	}

	twerr := twirp.NewError(code, msg)
	twerr = twerr.WithMeta("http_error_from_intermediary", "true") // to easily know if this error was from intermediary
	twerr = twerr.WithMeta("status_code", strconv.Itoa(status))
	if isHTTPRedirect(status) {
		twerr = twerr.WithMeta("location", bodyOrLocation)
	} else {
		twerr = twerr.WithMeta("body", bodyOrLocation)
	}
	return twerr
}
func isHTTPRedirect(status int) bool {
	return status >= 300 && status <= 399
}

// wrappedError implements the github.com/pkg/errors.Causer interface, allowing errors to be
// examined for their root cause.
type wrappedError struct {
	msg   string
	cause error
}

func wrapErr(err error, msg string) error { return &wrappedError{msg: msg, cause: err} }
func (e *wrappedError) Cause() error      { return e.cause }
func (e *wrappedError) Error() string     { return e.msg + ": " + e.cause.Error() }

// clientError adds consistency to errors generated in the client
func clientError(desc string, err error) twirp.Error {
	return twirp.InternalErrorWith(wrapErr(err, desc))
}

// badRouteError is used when the twirp server cannot route a request
func badRouteError(msg string, method, url string) twirp.Error {
	err := twirp.NewError(twirp.BadRoute, msg)
	err = err.WithMeta("twirp_invalid_route", method+" "+url)
	return err
}

// The standard library will, by default, redirect requests (including POSTs) if it gets a 302 or
// 303 response, and also 301s in go1.8. It redirects by making a second request, changing the
// method to GET and removing the body. This produces very confusing error messages, so instead we
// set a redirect policy that always errors. This stops Go from executing the redirect.
//
// We have to be a little careful in case the user-provided http.Client has its own CheckRedirect
// policy - if so, we'll run through that policy first.
//
// Because this requires modifying the http.Client, we make a new copy of the client and return it.
func withoutRedirects(in *http.Client) *http.Client {
	copy := *in
	copy.CheckRedirect = func(req *http.Request, via []*http.Request) error {
		if in.CheckRedirect != nil {
			// Run the input's redirect if it exists, in case it has side effects, but ignore any error it
			// returns, since we want to use ErrUseLastResponse.
			err := in.CheckRedirect(req, via)
			_ = err // Silly, but this makes sure generated code passes errcheck -blank, which some people use.
		}
		return http.ErrUseLastResponse
	}
	return &copy
}

// doProtobufRequest is common code to make a request to the remote twirp service.
func doProtobufRequest(ctx context.Context, client HTTPClient, url string, in, out proto.Message) (err error) {
	reqBodyBytes, err := proto.Marshal(in)
	if err != nil {
		return clientError("failed to marshal proto request", err)
	}
	reqBody := bytes.NewBuffer(reqBodyBytes)
	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}

	req, err := newRequest(ctx, url, reqBody, "application/protobuf")
	if err != nil {
		return clientError("could not build request", err)
	}
	resp, err := client.Do(req)
	if err != nil {
		return clientError("failed to do request", err)
	}

	defer func() {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = clientError("failed to close response body", cerr)
		}
	}()

	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}

	if resp.StatusCode != 200 {
		return errorFromResponse(resp)
	}

	respBodyBytes, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		return clientError("failed to read response body", err)
	}
	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}

	if err = proto.Unmarshal(respBodyBytes, out); err != nil {
		return clientError("failed to unmarshal proto response", err)
	}
	return nil
}

// doJSONRequest is common code to make a request to the remote twirp service.
func doJSONRequest(ctx context.Context, client HTTPClient, url string, in, out proto.Message) (err error) {
	reqBody := bytes.NewBuffer(nil)
	marshaler := &jsonpb.Marshaler{OrigName: true}
	if err = marshaler.Marshal(reqBody, in); err != nil {
		return clientError("failed to marshal json request", err)
	}
	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}

	req, err := newRequest(ctx, url, reqBody, "application/json")
	if err != nil {
		return clientError("could not build request", err)
	}
	resp, err := client.Do(req)
	if err != nil {
		return clientError("failed to do request", err)
	}

	defer func() {
		cerr := resp.Body.Close()
		if err == nil && cerr != nil {
			err = clientError("failed to close response body", cerr)
		}
	}()

	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}

	if resp.StatusCode != 200 {
		return errorFromResponse(resp)
	}

	unmarshaler := jsonpb.Unmarshaler{AllowUnknownFields: true}
	if err = unmarshaler.Unmarshal(resp.Body, out); err != nil {
		return clientError("failed to unmarshal json response", err)
	}
	if err = ctx.Err(); err != nil {
		return clientError("aborted because context was done", err)
	}
	return nil
}

// Call twirp.ServerHooks.RequestReceived if the hook is available
func callRequestReceived(ctx context.Context, h *twirp.ServerHooks) (context.Context, error) {
	if h == nil || h.RequestReceived == nil {
		return ctx, nil
	}
	return h.RequestReceived(ctx)
}

// Call twirp.ServerHooks.RequestRouted if the hook is available
func callRequestRouted(ctx context.Context, h *twirp.ServerHooks) (context.Context, error) {
	if h == nil || h.RequestRouted == nil {
		return ctx, nil
	}
	return h.RequestRouted(ctx)
}

// Call twirp.ServerHooks.ResponsePrepared if the hook is available
func callResponsePrepared(ctx context.Context, h *twirp.ServerHooks) context.Context {
	if h == nil || h.ResponsePrepared == nil {
		return ctx
	}
	return h.ResponsePrepared(ctx)
}

// Call twirp.ServerHooks.ResponseSent if the hook is available
func callResponseSent(ctx context.Context, h *twirp.ServerHooks) {
	if h == nil || h.ResponseSent == nil {
		return
	}
	h.ResponseSent(ctx)
}

// Call twirp.ServerHooks.Error if the hook is available
func callError(ctx context.Context, h *twirp.ServerHooks, err twirp.Error) context.Context {
	if h == nil || h.Error == nil {
		return ctx
	}
	return h.Error(ctx, err)
}

var twirpFileDescriptor0 = []byte{
	// 803 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xc1, 0x4e, 0xdb, 0x4a,
	0x14, 0xc5, 0x0e, 0x84, 0xf8, 0x9a, 0x84, 0x30, 0x3c, 0xf1, 0x4c, 0x78, 0x24, 0xc1, 0xbc, 0x87,
	0xf2, 0x50, 0x15, 0xa9, 0x54, 0xdd, 0x74, 0x17, 0x08, 0xa2, 0x51, 0x81, 0x20, 0x17, 0x50, 0x55,
	0xa1, 0x46, 0x4e, 0x3c, 0x42, 0xa3, 0x18, 0xdb, 0xb5, 0x9d, 0xa8, 0xd9, 0x54, 0xfc, 0x43, 0x3f,
	0xa7, 0x8b, 0xfe, 0x50, 0x77, 0xfd, 0x81, 0xca, 0x33, 0x63, 0xc7, 0x4e, 0xe2, 0x84, 0xaa, 0xea,
	0x2e, 0x73, 0xe7, 0xcc, 0xb9, 0x67, 0xee, 0x3d, 0x77, 0x62, 0x58, 0x37, 0xf0, 0x90, 0xf4, 0xb0,
	0x8b, 0xef, 0xeb, 0x8e, 0x6b, 0xfb, 0x36, 0x92, 0xa2, 0x80, 0xfa, 0x5d, 0x04, 0x74, 0x62, 0xea,
	0xe4, 0xa1, 0x49, 0x43, 0x1a, 0xfe, 0x38, 0xc0, 0x9e, 0x8f, 0xf6, 0x60, 0x8d, 0x61, 0x3a, 0xbe,
	0xdd, 0xc7, 0x96, 0x22, 0x54, 0x85, 0x9a, 0xa4, 0xc9, 0x2c, 0x76, 0x1d, 0x84, 0xd0, 0x36, 0xe4,
	0x06, 0x1e, 0x76, 0x3b, 0x03, 0x62, 0x28, 0x22, 0xdd, 0x5e, 0x0d, 0xd6, 0x37, 0xc4, 0x40, 0xc7,
	0x90, 0x33, 0xed, 0x9e, 0xee, 0x13, 0xdb, 0x52, 0x32, 0x55, 0xa1, 0x26, 0x1f, 0x1d, 0xd4, 0xc7,
	0x1a, 0xa6, 0xd3, 0xd5, 0xcf, 0x39, 0x5a, 0x8b, 0xce, 0x05, 0x1c, 0xf8, 0x93, 0x63, 0x7b, 0x03,
	0x17, 0x2b, 0xcb, 0x55, 0xa1, 0x56, 0x58, 0xc4, 0x71, 0xca, 0xd1, 0x5a, 0x74, 0x0e, 0xfd, 0x07,
	0x85, 0xae, 0x6b, 0xf7, 0xb1, 0xdb, 0xd1, 0x0d, 0xc3, 0xc5, 0x9e, 0xa7, 0xac, 0x50, 0xa1, 0x79,
	0x16, 0x6d, 0xb0, 0x60, 0xa9, 0x09, 0xb9, 0x50, 0x00, 0xfa, 0x07, 0x24, 0xd3, 0xb6, 0xee, 0x89,
	0x3f, 0x30, 0x30, 0xbd, 0xb5, 0xa0, 0x8d, 0x03, 0xa8, 0x04, 0x39, 0x53, 0xf7, 0xd9, 0xa6, 0x48,
	0x37, 0xa3, 0xb5, 0xba, 0x0f, 0xb9, 0x50, 0x02, 0x02, 0xc8, 0xb6, 0x2e, 0x9b, 0xed, 0xb6, 0x56,
	0x5c, 0x42, 0x32, 0xac, 0xb6, 0x6f, 0xae, 0xe9, 0x42, 0x50, 0xbf, 0x08, 0xb0, 0x99, 0xd0, 0xee,
	0x39, 0xb6, 0xe5, 0x61, 0x54, 0x83, 0x22, 0x2d, 0xa6, 0xe3, 0x92, 0xa1, 0xee, 0xe3, 0x4e, 0x1f,
	0x8f, 0x78, 0xcd, 0x0b, 0x41, 0xfc, 0x8a, 0x85, 0xdf, 0xe0, 0x11, 0x3a, 0x80, 0x75, 0x86, 0x1c,
	0x74, 0x4d, 0xd2, 0xa3, 0x40, 0x56, 0xfd, 0x3c, 0x05, 0xd2, 0x68, 0x80, 0x3b, 0x84, 0x0d, 0xde,
	0xc1, 0x18, 0x32, 0x43, 0x91, 0xdc, 0x0f, 0x11, 0x56, 0xed, 0xc2, 0xa6, 0x86, 0x87, 0x76, 0x1f,
	0xff, 0xb2, 0x09, 0x66, 0xe9, 0x16, 0x67, 0xe9, 0x56, 0xb7, 0xe0, 0xaf, 0x64, 0x0e, 0x76, 0x73,
	0xf5, 0x9b, 0x00, 0xf2, 0xa9, 0xe5, 0x13, 0xdf, 0xc4, 0x0f, 0xd8, 0xf2, 0xd1, 0x0e, 0x48, 0x1e,
	0xb6, 0x3c, 0xdb, 0xed, 0x10, 0x83, 0x66, 0xcc, 0x6b, 0x39, 0x16, 0x68, 0x19, 0xe8, 0x25, 0x64,
	0xf5, 0x1e, 0xb5, 0x95, 0x48, 0x2d, 0xb1, 0x1b, 0xb3, 0x44, 0x8c, 0xa4, 0xde, 0xa0, 0x20, 0x8d,
	0x83, 0x11, 0x82, 0xe5, 0x2e, 0xb1, 0x3c, 0x25, 0x53, 0xcd, 0xd4, 0x04, 0x8d, 0xfe, 0x0e, 0x5a,
	0x49, 0x2c, 0x1f, 0xbb, 0x43, 0xdd, 0xa4, 0xfe, 0xca, 0x6b, 0xd1, 0x5a, 0x7d, 0x06, 0x59, 0xc6,
	0x80, 0x24, 0x58, 0x79, 0xfb, 0xba, 0xa1, 0x9d, 0x16, 0x97, 0xd0, 0x2a, 0x64, 0x8e, 0x5b, 0x97,
	0x45, 0x01, 0x15, 0x00, 0x2e, 0xda, 0xb7, 0xad, 0xcb, 0xb3, 0x4e, 0xe3, 0xf6, 0xac, 0x28, 0xaa,
	0x77, 0x50, 0x3e, 0x71, 0xb1, 0xee, 0xe3, 0x98, 0x82, 0x2b, 0xdb, 0x24, 0xbd, 0x51, 0x58, 0xc8,
	0x57, 0xb0, 0x86, 0xc7, 0x7b, 0x9e, 0x22, 0x54, 0x33, 0x35, 0xf9, 0x68, 0x6b, 0xb6, 0x78, 0x2d,
	0x81, 0x55, 0x3f, 0x43, 0x25, 0x95, 0x9d, 0x9b, 0x67, 0x07, 0x24, 0x87, 0x46, 0xc2, 0x92, 0x49,
	0x5a, 0x8e, 0x05, 0x5a, 0x06, 0xaa, 0x80, 0x3c, 0xdd, 0x1c, 0x70, 0xc6, 0x86, 0xda, 0x05, 0x98,
	0x72, 0x88, 0xe4, 0x44, 0xde, 0xf8, 0x00, 0xe5, 0x26, 0x36, 0xf1, 0x9c, 0xdb, 0xfd, 0x56, 0x7a,
	0x75, 0x0f, 0x2a, 0xa9, 0xfc, 0xdc, 0x22, 0x55, 0x28, 0x9f, 0x13, 0xcf, 0x9f, 0x04, 0x10, 0xec,
	0x71, 0x09, 0xea, 0x0f, 0x01, 0x2a, 0xa9, 0x10, 0x5e, 0xa5, 0x0b, 0x60, 0xaa, 0x08, 0x0e, 0x1b,
	0xf0, 0x3c, 0xd6, 0x80, 0x05, 0xa7, 0xeb, 0x5c, 0x52, 0x44, 0x51, 0x7a, 0x14, 0x20, 0xcb, 0x82,
	0xf3, 0x0b, 0x30, 0xd9, 0x7b, 0xf1, 0xe9, 0xbd, 0x5f, 0xd4, 0x9a, 0x47, 0x01, 0x50, 0xfc, 0xf0,
	0x1f, 0x18, 0x5b, 0x2a, 0x21, 0xbc, 0x1b, 0x1b, 0xa0, 0x40, 0x02, 0xbf, 0x9c, 0xa7, 0xde, 0x81,
	0xd2, 0x70, 0x1c, 0x73, 0x94, 0x90, 0xc1, 0x0b, 0xfe, 0x04, 0x1d, 0x49, 0x76, 0x71, 0x92, 0x7d,
	0x07, 0xb6, 0xd9, 0x9b, 0x31, 0x83, 0xfe, 0xe8, 0xeb, 0x0a, 0xa0, 0xf0, 0x2d, 0xb9, 0x27, 0x9e,
	0xef, 0xb2, 0x07, 0xfc, 0x1c, 0xe4, 0xd8, 0x03, 0x8b, 0x76, 0xe7, 0xfe, 0x69, 0x94, 0xca, 0x69,
	0xdb, 0xfc, 0x0e, 0x6d, 0x58, 0x8b, 0xbf, 0x5a, 0x28, 0x8e, 0x9f, 0xf1, 0x64, 0x96, 0x2a, 0xa9,
	0xfb, 0x9c, 0xd0, 0x81, 0xbf, 0x53, 0xc6, 0x19, 0xfd, 0x1f, 0xd7, 0x32, 0xf7, 0x41, 0x29, 0x1d,
	0x3e, 0x05, 0x3a, 0xce, 0x98, 0x32, 0x60, 0x89, 0x8c, 0xf3, 0x87, 0x3c, 0x91, 0x71, 0xc1, 0xbc,
	0x06, 0x19, 0x53, 0xc6, 0x29, 0x91, 0x71, 0xfe, 0x4c, 0x27, 0x32, 0x2e, 0x9a, 0xed, 0x5b, 0x28,
	0x4e, 0xda, 0x10, 0xa5, 0xfc, 0x37, 0x84, 0xf4, 0xfb, 0xb1, 0xed, 0x54, 0x0b, 0xbf, 0x83, 0x8d,
	0x29, 0x03, 0x2e, 0x22, 0xfe, 0x77, 0xca, 0x02, 0x33, 0x98, 0x8f, 0xe5, 0xf7, 0xe3, 0x8f, 0xb0,
	0x6e, 0x96, 0x7e, 0x96, 0xbd, 0xf8, 0x19, 0x00, 0x00, 0xff, 0xff, 0xa0, 0x0a, 0x1a, 0x8a, 0xa9,
	0x09, 0x00, 0x00,
}
